name: labeling_env
channels:
- conda-forge
dependencies:
  - python=3.10
  - scipy
  - pip
  - pip:
    - open3d
    - ipykernel
    - torch --index-url https://download.pytorch.org/whl/cu126
    - torchvision --index-url https://download.pytorch.org/whl/cu126
    - torchaudio --index-url https://download.pytorch.org/whl/cu126
    - opencv-contrib-python
    - coacd
    - trimesh
    - kornia
    - mediapipe
    - munch
    - transformers